version: '3.7'

services:
  webapp:
    environment:
      - FLASK_ENV=production
  nginx:
    image: typeai/zombie-nginx
    restart: always
    depends_on:
      - webapp
    volumes:
      - ./webapp-zombie-prod.yml:/etc/appconf/nginx.yml:ro
    environment:
      - "LETSENCRYPT_EMAIL=test@testconf.com"
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
