version: '3.7'
services:
  webapp:
    container_name: flask-application
    build: .
    restart: always
    networks:
      - back-tier

  nginx:
    container_name: nginx-server
    image: typeai/zombie-nginx
    restart: always
    networks:
      - back-tier
    depends_on:
      - webapp

networks:
  back-tier: null
